excel:
  data_sheet_name: Data
  notes_sheet_name: Notes

messages:
  requests:
    account: # name of the account
    mailbox: # name of the mailbox
    server:  # name of the host server
  notifications:
    send: true
    sender: # mail address of the sender
    subject: # notification subject
    host: # host server of the sender account
    port: # port nmber of the host server
